In [1]:
import pandas as pd

In [2]:
# Load the dataset
data = pd.read_csv("students.csv")

# Display the first five records
data.head()

,Timestamp,Full Name,Department,Skills,Programming Languages Known,Career Interest,Favourite Course,Career Goal,CGPA,Number of Carryovers
0,NaN,John,Computer Science,"HTML, CSS, Python, Problem Solving, UI/UX Design","Python, Java, C#, PHP",Web Development,Front end development,I love front end development,3.56,0
1,NaN,Prince otum,Computer Science,Python,Python,Web Development,Database management,Artificial intelligence,3.32,0
2,NaN,Flash,Computer Science,"HTML, CSS, JavaScript, Problem Solving, Database","Python, Java, C++, C#",Web Development,Cloud computing,Project Management,3.49,0
3,NaN,Chioma Monica,Computer Science,"Python, Problem Solving, Database,","Python, Java, C++",Artificial Intelligence,Artificial intelligence,Data analysis,3.45,0
4,NaN,Egwuatu Kelechi Blessed,Computer Science,UI/UX Design,HTML,Mobile Development,Frontend Development,Full stack,3.27,0

In [3]:
# Display column names
print("Original Columns:")
print(data.columns)

# Remove Timestamp column if it exists
if "Timestamp" in data.columns:
    data = data.drop(columns=["Timestamp"])

# Remove completely empty columns
data = data.dropna(axis=1, how="all")

# Remove duplicate records
data = data.drop_duplicates()

# Remove rows with missing values
data = data.dropna()

print("\nDataset cleaned successfully.")

# Display cleaned data
data.head()

Original Columns:
Index(['Timestamp', 'Full Name', 'Department', 'Skills',
       'Programming Languages Known', 'Career Interest', 'Favourite Course',
       'Career Goal', 'CGPA', 'Number of Carryovers'],
      dtype='object')

Dataset cleaned successfully.

,Full Name,Department,Skills,Programming Languages Known,Career Interest,Favourite Course,Career Goal,CGPA,Number of Carryovers
0,John,Computer Science,"HTML, CSS, Python, Problem Solving, UI/UX Design","Python, Java, C#, PHP",Web Development,Front end development,I love front end development,3.56,0
1,Prince otum,Computer Science,Python,Python,Web Development,Database management,Artificial intelligence,3.32,0
2,Flash,Computer Science,"HTML, CSS, JavaScript, Problem Solving, Database","Python, Java, C++, C#",Web Development,Cloud computing,Project Management,3.49,0
3,Chioma Monica,Computer Science,"Python, Problem Solving, Database,","Python, Java, C++",Artificial Intelligence,Artificial intelligence,Data analysis,3.45,0
4,Egwuatu Kelechi Blessed,Computer Science,UI/UX Design,HTML,Mobile Development,Frontend Development,Full stack,3.27,0

In [4]:
print("="*60)
print("DATASET SUMMARY")
print("="*60)

print("Total Number of Students:", len(data))

print("\nDepartments")
print(data["Department"].value_counts())

print("\nAverage CGPA")
print(round(data["CGPA"].mean(),2))

print("\nHighest CGPA")
print(data["CGPA"].max())

print("\nLowest CGPA")
print(data["CGPA"].min())

============================================================
DATASET SUMMARY
============================================================
Total Number of Students: 102

Departments
Department
Computer Science           44
Information Technology     16
Business Administration    15
Electrical Engineering     11
Computer Engineering        9
Software Engineering        7
Name: count, dtype: int64

Average CGPA
3.33

Highest CGPA
5.0

Lowest CGPA
1.09

In [5]:
for index, row in data.iterrows():

    print("\n" + "="*60)

    print("Student Name:", row["Full Name"])
    print("Department:", row["Department"])
    print("Skills:", row["Skills"])
    print("Programming Languages:", row["Programming Languages Known"])
    print("Career Interest:", row["Career Interest"])
    print("Favourite Course:", row["Favourite Course"])
    print("Career Goal:", row["Career Goal"])
    print("CGPA:", row["CGPA"])
    print("Carryovers:", row["Number of Carryovers"])

============================================================
Student Name: John
Department: Computer Science
Skills: HTML, CSS, Python, Problem Solving, UI/UX Design
Programming Languages: Python, Java, C#, PHP
Career Interest: Web Development
Favourite Course: Front end development
Career Goal: I love front end development
CGPA: 3.56
Carryovers: 0

============================================================
Student Name: Prince otum
Department: Computer Science
Skills: Python
Programming Languages: Python
Career Interest: Web Development
Favourite Course: Database management
Career Goal: Artificial intelligence
CGPA: 3.32
Carryovers: 0

============================================================
Student Name: Flash
Department: Computer Science
Skills: HTML, CSS, JavaScript, Problem Solving, Database
Programming Languages: Python, Java, C++, C#
Career Interest: Web Development
Favourite Course: Cloud computing
Career Goal: Project Management
CGPA: 3.49
Carryovers: 0

============================================================
Student Name: Chioma Monica
Department: Computer Science
Skills: Python, Problem Solving, Database,
Programming Languages: Python, Java, C++
Career Interest: Artificial Intelligence
Favourite Course: Artificial intelligence
Career Goal: Data analysis
CGPA: 3.45
Carryovers: 0

============================================================
Student Name: Egwuatu Kelechi Blessed
Department: Computer Science
Skills: UI/UX Design
Programming Languages: HTML
Career Interest: Mobile Development
Favourite Course: Frontend Development
Career Goal: Full stack
CGPA: 3.27
Carryovers: 0

============================================================
Student Name: Fred
Department: Computer Science
Skills: Cybersecurity
Programming Languages: Python
Career Interest: Cyber Security
Favourite Course: SOC analyst
Career Goal: Cybersecurity
CGPA: 3.39
Carryovers: 0

============================================================
Student Name: Rufus Deborah ogbonnaya
Department: Computer Science
Skills: HTML, Python, Database
Programming Languages: Python
Career Interest: Cloud Computing
Favourite Course: Python programming language
Career Goal: Networking and database management
CGPA: 3.21
Carryovers: 0

============================================================
Student Name: Sunday Samuel Ogo
Department: Computer Science
Skills: Cloud computing
Programming Languages: Python
Career Interest: Cloud Computing
Favourite Course: Cloud computing 1
Career Goal: Business
CGPA: 3.05
Carryovers: 0

============================================================
Student Name: Isaac chinonso Mark
Department: Computer Science
Skills: HTML, CSS, Python
Programming Languages: Python, Java
Career Interest: Web Development
Favourite Course: Front end development
Career Goal: Web developer
CGPA: 3.35
Carryovers: 0

============================================================
Student Name: Ibekwe Mark Uchenna
Department: Computer Science
Skills: HTML, CSS
Programming Languages: Python
Career Interest: Software Engineering
Favourite Course: MATHS AND STAT
Career Goal: Software Developer
CGPA: 2.7
Carryovers: 1

============================================================
Student Name: Nwabueze Emmanuel
Department: Computer Science
Skills: UI/UX Design
Programming Languages: Python, Java
Career Interest: Web Development
Favourite Course: Python
Career Goal: Become tech guru
CGPA: 3.5
Carryovers: 0

============================================================
Student Name: Ebeke Stephen agha
Department: Computer Science
Skills: Python
Programming Languages: Python
Career Interest: Cloud Computing
Favourite Course: Data management
Career Goal: PGD
CGPA: 3.12
Carryovers: 0

============================================================
Student Name: Samuel chinonso
Department: Computer Science
Skills: JavaScript
Programming Languages: Python
Career Interest: Web Development
Favourite Course: Database management
Career Goal: Software development
CGPA: 3.0
Carryovers: 0

============================================================
Student Name: Chinenye David
Department: Computer Science
Skills: HTML
Programming Languages: Python
Career Interest: Web Development
Favourite Course: Python programming
Career Goal: Frontend Developer
CGPA: 4.0
Carryovers: 0

============================================================
Student Name: Vincent Jeremiah Chidera
Department: Computer Science
Skills: HTML
Programming Languages: Python
Career Interest: Cloud Computing
Favourite Course: Network
Career Goal: cloud computing
CGPA: 1.09
Carryovers: 0

============================================================
Student Name: Jeff Ekong
Department: Computer Science
Skills: Python, Problem Solving
Programming Languages: C#, Dart
Career Interest: Web Development
Favourite Course: Data base
Career Goal: To be a Software Engineer
CGPA: 3.5
Carryovers: 0

============================================================
Student Name: Idam Roseline
Department: Computer Science
Skills: HTML, CSS, JavaScript, UI/UX Design
Programming Languages: C++
Career Interest: UI/UX Design
Favourite Course: AI
Career Goal: Developer
CGPA: 3.5
Carryovers: 0

============================================================
Student Name: Emmanuel
Department: Computer Science
Skills: HTML, CSS, Python
Programming Languages: Python, Java, C#
Career Interest: Web Development
Favourite Course: Data base
Career Goal: Web development
CGPA: 3.23
Carryovers: 0

============================================================
Student Name: Rhema
Department: Computer Science
Skills: HTML, CSS, JavaScript, UI/UX Design
Programming Languages: PHP
Career Interest: Web Development
Favourite Course: UI/UX Design
Career Goal: UI/UX Design
CGPA: 3.5
Carryovers: 0

============================================================
Student Name: NWIBO SALOME OGBAGA
Department: Computer Science
Skills: HTML
Programming Languages: PHP
Career Interest: Web Development
Favourite Course: Database design
Career Goal: Web developer
CGPA: 3.06
Carryovers: 0

============================================================
Student Name: Okoro wisdom
Department: Computer Science
Skills: Database
Programming Languages: Python
Career Interest: Software Engineering
Favourite Course: Statistical analysis
Career Goal: Compute engineering
CGPA: 4.0
Carryovers: 0

============================================================
Student Name: Okorie joe
Department: Computer Science
Skills: Database
Programming Languages: Python
Career Interest: Web Development
Favourite Course: Database management
Career Goal: Python
CGPA: 2.8
Carryovers: 0

============================================================
Student Name: Ekene madu
Department: Computer Science
Skills: JavaScript
Programming Languages: Java
Career Interest: Mobile Development
Favourite Course: JavaScript
Career Goal: Software Engineering
CGPA: 3.4
Carryovers: 0

============================================================
Student Name: Jonathan Samuel
Department: Software Engineering
Skills: CSS
Programming Languages: Java, C++
Career Interest: Web Development
Favourite Course: Database management
Career Goal: Css
CGPA: 4.0
Carryovers: 0

============================================================
Student Name: Mark King
Department: Computer Science
Skills: JavaScript
Programming Languages: C#
Career Interest: Artificial Intelligence
Favourite Course: AI
Career Goal: AI
CGPA: 4.1
Carryovers: 0

============================================================
Student Name: Samuel Elizabeth
Department: Computer Science
Skills: Problem Solving
Programming Languages: PHP
Career Interest: Software Engineering
Favourite Course: Front-End
Career Goal: Software Designer
CGPA: 5.0
Carryovers: 0

============================================================
Student Name: Amaka David
Department: Computer Science
Skills: Database
Programming Languages: Kotlin
Career Interest: Cloud Computing
Favourite Course: Database management
Career Goal: Database designer
CGPA: 4.01
Carryovers: 1

============================================================
Student Name: Okoro Emmanuel O
Department: Computer Science
Skills: HTML
Programming Languages: Python
Career Interest: Cyber Security
Favourite Course: Database design
Career Goal: Mathematics
CGPA: 4.0
Carryovers: 0

============================================================
Student Name: Mark godson
Department: Information Technology
Skills: UI/UX Design
Programming Languages: C++
Career Interest: UI/UX Design
Favourite Course: Gns
Career Goal: Business
CGPA: 3.6
Carryovers: 0

============================================================
Student Name: Emmanuel Victoria
Department: Computer Science
Skills: HTML, CSS, JavaScript
Programming Languages: Python, Java
Career Interest: Web Development
Favourite Course: Software engineer
Career Goal: Full stack Developer
CGPA: 3.7
Carryovers: 0

============================================================
Student Name: Williams ugo
Department: Computer Engineering
Skills: HTML, Python, Problem Solving
Programming Languages: Python, C++, C#
Career Interest: Artificial Intelligence
Favourite Course: Artificial Intelligence
Career Goal: Google expert
CGPA: 3.0
Carryovers: 0

============================================================
Student Name: Victor urom
Department: Electrical Engineering
Skills: HTML, Python, JavaScript
Programming Languages: Python, Java, C++
Career Interest: Artificial Intelligence
Favourite Course: Artificial Intelligence
Career Goal: Web developer
CGPA: 2.8
Carryovers: 1

============================================================
Student Name: Chioma egwu
Department: Computer Engineering
Skills: HTML, CSS, Python, Problem Solving
Programming Languages: Python, Java, C++, PHP
Career Interest: Artificial Intelligence
Favourite Course: Web development
Career Goal: Web developer
CGPA: 3.4
Carryovers: 0

============================================================
Student Name: Agwu Theresa
Department: Computer Science
Skills: JavaScript
Programming Languages: Python, Java, PHP
Career Interest: Web Development
Favourite Course: Data base management
Career Goal: Cyber security
CGPA: 3.61
Carryovers: 1

============================================================
Student Name: Onyekachi Nobel
Department: Information Technology
Skills: HTML
Programming Languages: Dart
Career Interest: Artificial Intelligence
Favourite Course: Artificial intelligence
Career Goal: Web development
CGPA: 4.2
Carryovers: 2

============================================================
Student Name: Tessa chukwubuike
Department: Business Administration
Skills: HTML
Programming Languages: PHP
Career Interest: Mobile Development
Favourite Course: Mobile administration
Career Goal: Public administration
CGPA: 2.9
Carryovers: 0

============================================================
Student Name: Favour
Department: Electrical Engineering
Skills: HTML, CSS, JavaScript
Programming Languages: Python, Java, C++, C#
Career Interest: Artificial Intelligence
Favourite Course: Mobile development
Career Goal: Mobile Developer
CGPA: 3.2
Carryovers: 0

============================================================
Student Name: Peter Emmanuel
Department: Software Engineering
Skills: HTML
Programming Languages: C++
Career Interest: Web Development
Favourite Course: Data Structure and Algorithm
Career Goal: Full stack developer
CGPA: 3.5
Carryovers: 0

============================================================
Student Name: Ewa divine
Department: Information Technology
Skills: HTML, CSS, Problem Solving, Database
Programming Languages: Java, C++, PHP
Career Interest: Cyber Security
Favourite Course: Cyber security
Career Goal: Analyst
CGPA: 3.5
Carryovers: 0

============================================================
Student Name: Desmond Blessing
Department: Business Administration
Skills: Database
Programming Languages: PHP
Career Interest: Data Science
Favourite Course: SQL fundamentals
Career Goal: Financial analyst
CGPA: 3.45
Carryovers: 1

============================================================
Student Name: Divine
Department: Computer Engineering
Skills: HTML, CSS, Python, Problem Solving
Programming Languages: Java, C++, C#, Dart
Career Interest: Software Engineering
Favourite Course: Artificial Intelligence
Career Goal: Cyber security
CGPA: 4.0
Carryovers: 0

============================================================
Student Name: Agha
Department: Business Administration
Skills: HTML, Python, JavaScript, Problem Solving, Database
Programming Languages: Java, C#, Kotlin
Career Interest: Mobile Development
Favourite Course: Mobile Development
Career Goal: Cyber security
CGPA: 2.5
Carryovers: 2

============================================================
Student Name: Thompson
Department: Information Technology
Skills: CSS, Python, Problem Solving, Database
Programming Languages: PHP, Dart
Career Interest: Artificial Intelligence
Favourite Course: Artificial Intelligence
Career Goal: Data Science
CGPA: 3.2
Carryovers: 0

============================================================
Student Name: Adline
Department: Electrical Engineering
Skills: Circuit analysis
Programming Languages: Dart
Career Interest: Automation and control
Favourite Course: PCB design
Career Goal: HR and Admin
CGPA: 2.49
Carryovers: 1

============================================================
Student Name: Precious
Department: Information Technology
Skills: HTML, CSS
Programming Languages: Python, C++, C#
Career Interest: Artificial Intelligence
Favourite Course: UI/UX
Career Goal: Data entry
CGPA: 3.5
Carryovers: 0

============================================================
Student Name: Abdul Lawal
Department: Computer Engineering
Skills: Python
Programming Languages: Kotlin
Career Interest: Data Science
Favourite Course: Statistics and probability
Career Goal: Financial analyst
CGPA: 3.0
Carryovers: 2

============================================================
Student Name: Rosemary
Department: Computer Science
Skills: HTML, Python, Problem Solving
Programming Languages: Java, C++, PHP
Career Interest: Cyber Security
Favourite Course: Database
Career Goal: Artificial Intelligence
CGPA: 2.8
Carryovers: 0

============================================================
Student Name: Rhema
Department: Information Technology
Skills: CSS
Programming Languages: PHP
Career Interest: Artificial Intelligence
Favourite Course: Cyber Security
Career Goal: Network Engineer
CGPA: 4.0
Carryovers: 0

============================================================
Student Name: Chibuzor
Department: Business Administration
Skills: HTML, Python, JavaScript, UI/UX Design
Programming Languages: Java, C++, PHP
Career Interest: Software Engineering
Favourite Course: Cyber security
Career Goal: Web development
CGPA: 2.95
Carryovers: 0

============================================================
Student Name: Joyce
Department: Computer Science
Skills: HTML
Programming Languages: C++
Career Interest: Cyber Security
Favourite Course: Programming
Career Goal: Computer Architecture
CGPA: 5.0
Carryovers: 0

============================================================
Student Name: Ugochi
Department: Electrical Engineering
Skills: Python, JavaScript, Problem Solving, UI/UX Design
Programming Languages: Python, C++, C#, PHP, Dart
Career Interest: Data Science
Favourite Course: Backend development
Career Goal: Full stack Development
CGPA: 3.6
Carryovers: 0

============================================================
Student Name: Splendor
Department: Computer Engineering
Skills: JavaScript
Programming Languages: PHP
Career Interest: Mobile Development
Favourite Course: Electrical circuit
Career Goal: Software engineer
CGPA: 2.45
Carryovers: 0

============================================================
Student Name: Charity
Department: Computer Science
Skills: HTML, CSS, Python, Problem Solving
Programming Languages: Python, Java, C++
Career Interest: Data Science
Favourite Course: Front-End development
Career Goal: Database management
CGPA: 3.0
Carryovers: 0

============================================================
Student Name: Rhems
Department: Electrical Engineering
Skills: Problem Solving
Programming Languages: C#
Career Interest: Cloud Computing
Favourite Course: Auto Cad engineer
Career Goal: Software engineer
CGPA: 3.0
Carryovers: 0

============================================================
Student Name: Faith
Department: Business Administration
Skills: HTML, CSS, JavaScript, Problem Solving
Programming Languages: Python, C++, PHP
Career Interest: Web Development
Favourite Course: Database design
Career Goal: App development
CGPA: 3.52
Carryovers: 0

============================================================
Student Name: John
Department: Computer Science
Skills: JavaScript
Programming Languages: Kotlin
Career Interest: Software Engineering
Favourite Course: Cyber security
Career Goal: Front end developer
CGPA: 4.0
Carryovers: 0

============================================================
Student Name: Emmanuella
Department: Electrical Engineering
Skills: HTML, CSS, JavaScript
Programming Languages: Python, Java, C++, PHP, Kotlin
Career Interest: Web Development
Favourite Course: Networking
Career Goal: Database designer
CGPA: 3.5
Carryovers: 0

============================================================
Student Name: Hannah Clinton
Department: Electrical Engineering
Skills: UI/UX Design
Programming Languages: C#
Career Interest: Cloud Computing
Favourite Course: Power electronics
Career Goal: Information technology
CGPA: 3.0
Carryovers: 0

============================================================
Student Name: Rebecca
Department: Information Technology
Skills: Problem Solving
Programming Languages: Python
Career Interest: Cloud Computing
Favourite Course: Cloud computing
Career Goal: IT Support
CGPA: 3.0
Carryovers: 0

============================================================
Student Name: Faith Adams
Department: Information Technology
Skills: Problem Solving
Programming Languages: Kotlin
Career Interest: Software Engineering
Favourite Course: Networking
Career Goal: Network Engineer
CGPA: 3.0
Carryovers: 0

============================================================
Student Name: Goodness
Department: Computer Engineering
Skills: HTML, CSS, JavaScript, Problem Solving, Database
Programming Languages: Java, C++, C#, PHP, Dart
Career Interest: Web Development
Favourite Course: Operation research
Career Goal: App development
CGPA: 3.5
Carryovers: 0

============================================================
Student Name: Frederick
Department: Computer Science
Skills: CSS, Python, JavaScript, Problem Solving, UI/UX Design
Programming Languages: Java, C++, C#, Dart
Career Interest: Artificial Intelligence
Favourite Course: Database management
Career Goal: Front-End development
CGPA: 3.7
Carryovers: 0

============================================================
Student Name: Udu prince
Department: Information Technology
Skills: Python, JavaScript, Problem Solving, Database
Programming Languages: Python, C++, C#, Dart
Career Interest: Web Development
Favourite Course: Cyber security
Career Goal: Backend development
CGPA: 3.2
Carryovers: 0

============================================================
Student Name: Daniel Effiong
Department: Business Administration
Skills: CSS
Programming Languages: C#
Career Interest: Software Engineering
Favourite Course: Principles of management
Career Goal: Business analytics
CGPA: 3.0
Carryovers: 0

============================================================
Student Name: Agwu Victoria
Department: Software Engineering
Skills: HTML, Python, JavaScript, UI/UX Design
Programming Languages: C++, C#, PHP
Career Interest: Data Science
Favourite Course: Data Science
Career Goal: Solar engineering
CGPA: 2.3
Carryovers: 2

============================================================
Student Name: Felicia

In [6]:
for index, row in data.iterrows():

    name = row["Full Name"]
    skills = str(row["Skills"]).lower()
    languages = str(row["Programming Languages Known"]).lower()
    interest = str(row["Career Interest"]).lower()

    print("\n")
    print("="*60)
    print("COURSE RECOMMENDATION FOR", name.upper())
    print("="*60)

    print("\nRecommended Courses")

    if "web" in interest:
        print("- HTML")
        print("- CSS")
        print("- JavaScript")
        print("- React")

    elif "backend" in interest:
        print("- Python")
        print("- PHP")
        print("- Node.js")

    elif "data" in interest:
        print("- SQL")
        print("- Machine Learning")
        print("- Data Analysis")

    elif "cyber" in interest:
        print("- Ethical Hacking")
        print("- Network Security")

    elif "mobile" in interest:
        print("- Flutter")
        print("- Kotlin")

    else:
        print("- General Programming")

    print("\nRecommended Certifications")
    print("- Google Career Certificate")
    print("- Microsoft Learn")
    print("- Cisco Networking Academy")
    print("- freeCodeCamp")

============================================================
COURSE RECOMMENDATION FOR JOHN
============================================================

Recommended Courses
- HTML
- CSS
- JavaScript
- React

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR PRINCE OTUM
============================================================

Recommended Courses
- HTML
- CSS
- JavaScript
- React

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR FLASH
============================================================

Recommended Courses
- HTML
- CSS
- JavaScript
- React

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR CHIOMA MONICA
============================================================

Recommended Courses
- General Programming

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR EGWUATU KELECHI BLESSED
============================================================

Recommended Courses
- Flutter
- Kotlin

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR FRED
============================================================

Recommended Courses
- Ethical Hacking
- Network Security

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR RUFUS DEBORAH OGBONNAYA
============================================================

Recommended Courses
- General Programming

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR SUNDAY SAMUEL OGO
============================================================

Recommended Courses
- General Programming

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR ISAAC CHINONSO MARK
============================================================

Recommended Courses
- HTML
- CSS
- JavaScript
- React

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR IBEKWE MARK UCHENNA
============================================================

Recommended Courses
- General Programming

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR NWABUEZE EMMANUEL
============================================================

Recommended Courses
- HTML
- CSS
- JavaScript
- React

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR EBEKE STEPHEN AGHA
============================================================

Recommended Courses
- General Programming

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR SAMUEL CHINONSO
============================================================

Recommended Courses
- HTML
- CSS
- JavaScript
- React

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR CHINENYE DAVID
============================================================

Recommended Courses
- HTML
- CSS
- JavaScript
- React

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR VINCENT JEREMIAH CHIDERA
============================================================

Recommended Courses
- General Programming

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR JEFF EKONG
============================================================

Recommended Courses
- HTML
- CSS
- JavaScript
- React

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR IDAM ROSELINE
============================================================

Recommended Courses
- General Programming

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR EMMANUEL
============================================================

Recommended Courses
- HTML
- CSS
- JavaScript
- React

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR RHEMA
============================================================

Recommended Courses
- HTML
- CSS
- JavaScript
- React

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR NWIBO SALOME OGBAGA
============================================================

Recommended Courses
- HTML
- CSS
- JavaScript
- React

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR OKORO WISDOM
============================================================

Recommended Courses
- General Programming

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR OKORIE JOE
============================================================

Recommended Courses
- HTML
- CSS
- JavaScript
- React

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR EKENE MADU
============================================================

Recommended Courses
- Flutter
- Kotlin

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR JONATHAN SAMUEL
============================================================

Recommended Courses
- HTML
- CSS
- JavaScript
- React

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR MARK KING
============================================================

Recommended Courses
- General Programming

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR SAMUEL ELIZABETH
============================================================

Recommended Courses
- General Programming

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR AMAKA DAVID
============================================================

Recommended Courses
- General Programming

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR OKORO EMMANUEL O
============================================================

Recommended Courses
- Ethical Hacking
- Network Security

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR MARK GODSON
============================================================

Recommended Courses
- General Programming

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR EMMANUEL VICTORIA
============================================================

Recommended Courses
- HTML
- CSS
- JavaScript
- React

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR WILLIAMS UGO
============================================================

Recommended Courses
- General Programming

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR VICTOR UROM
============================================================

Recommended Courses
- General Programming

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR CHIOMA EGWU
============================================================

Recommended Courses
- General Programming

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR AGWU THERESA
============================================================

Recommended Courses
- HTML
- CSS
- JavaScript
- React

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR ONYEKACHI NOBEL
============================================================

Recommended Courses
- General Programming

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR TESSA CHUKWUBUIKE
============================================================

Recommended Courses
- Flutter
- Kotlin

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR FAVOUR
============================================================

Recommended Courses
- General Programming

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR PETER EMMANUEL
============================================================

Recommended Courses
- HTML
- CSS
- JavaScript
- React

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR EWA DIVINE
============================================================

Recommended Courses
- Ethical Hacking
- Network Security

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR DESMOND BLESSING
============================================================

Recommended Courses
- SQL
- Machine Learning
- Data Analysis

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR DIVINE
============================================================

Recommended Courses
- General Programming

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR AGHA
============================================================

Recommended Courses
- Flutter
- Kotlin

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR THOMPSON
============================================================

Recommended Courses
- General Programming

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR ADLINE
============================================================

Recommended Courses
- General Programming

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR PRECIOUS
============================================================

Recommended Courses
- General Programming

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR ABDUL LAWAL
============================================================

Recommended Courses
- SQL
- Machine Learning
- Data Analysis

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR ROSEMARY
============================================================

Recommended Courses
- Ethical Hacking
- Network Security

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR RHEMA
============================================================

Recommended Courses
- General Programming

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR CHIBUZOR
============================================================

Recommended Courses
- General Programming

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR JOYCE
============================================================

Recommended Courses
- Ethical Hacking
- Network Security

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR UGOCHI
============================================================

Recommended Courses
- SQL
- Machine Learning
- Data Analysis

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR SPLENDOR
============================================================

Recommended Courses
- Flutter
- Kotlin

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR CHARITY
============================================================

Recommended Courses
- SQL
- Machine Learning
- Data Analysis

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR RHEMS
============================================================

Recommended Courses
- General Programming

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR FAITH
============================================================

Recommended Courses
- HTML
- CSS
- JavaScript
- React

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR JOHN
============================================================

Recommended Courses
- General Programming

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR EMMANUELLA
============================================================

Recommended Courses
- HTML
- CSS
- JavaScript
- React

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR HANNAH CLINTON
============================================================

Recommended Courses
- General Programming

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR REBECCA
============================================================

Recommended Courses
- General Programming

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR FAITH ADAMS
============================================================

Recommended Courses
- General Programming

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp


============================================================
COURSE RECOMMENDATION FOR GOODNESS
============================================================

Recommended Courses
- HTML
- CSS
- JavaScript
- React

Recommended Certifications
- Google Career Certificate
- Microsoft Learn
- Cisco Networking Academy
- freeCodeCamp



In [7]:
for index, row in data.iterrows():

    cgpa = float(row["CGPA"])
    carryovers = int(row["Number of Carryovers"])

    print("\nStudent:", row["Full Name"])

    if cgpa >= 4.5:
        print("Performance: Excellent")

    elif cgpa >= 3.5:
        print("Performance: Very Good")

    elif cgpa >= 2.5:
        print("Performance: Good")

    else:
        print("Performance: Needs Improvement")

    if carryovers == 0:
        print("Academic Status: Excellent (No Carryovers)")

    elif carryovers <= 2:
        print("Academic Status: Fair")

    else:
        print("Academic Status: Needs Improvement")

Student: John
Performance: Very Good
Academic Status: Excellent (No Carryovers)

Student: Prince otum
Performance: Good
Academic Status: Excellent (No Carryovers)

Student: Flash
Performance: Good
Academic Status: Excellent (No Carryovers)

Student: Chioma Monica
Performance: Good
Academic Status: Excellent (No Carryovers)

Student: Egwuatu Kelechi Blessed
Performance: Good
Academic Status: Excellent (No Carryovers)

Student: Fred
Performance: Good
Academic Status: Excellent (No Carryovers)

Student: Rufus Deborah ogbonnaya
Performance: Good
Academic Status: Excellent (No Carryovers)

Student: Sunday Samuel Ogo
Performance: Good
Academic Status: Excellent (No Carryovers)

Student: Isaac chinonso Mark
Performance: Good
Academic Status: Excellent (No Carryovers)

Student: Ibekwe Mark Uchenna
Performance: Good
Academic Status: Fair

Student: Nwabueze Emmanuel
Performance: Very Good
Academic Status: Excellent (No Carryovers)

Student: Ebeke Stephen agha
Performance: Good
Academic Status: Excellent (No Carryovers)

Student: Samuel chinonso
Performance: Good
Academic Status: Excellent (No Carryovers)

Student: Chinenye David
Performance: Very Good
Academic Status: Excellent (No Carryovers)

Student: Vincent Jeremiah Chidera
Performance: Needs Improvement
Academic Status: Excellent (No Carryovers)

Student: Jeff Ekong
Performance: Very Good
Academic Status: Excellent (No Carryovers)

Student: Idam Roseline
Performance: Very Good
Academic Status: Excellent (No Carryovers)

Student: Emmanuel
Performance: Good
Academic Status: Excellent (No Carryovers)

Student: Rhema
Performance: Very Good
Academic Status: Excellent (No Carryovers)

Student: NWIBO SALOME OGBAGA
Performance: Good
Academic Status: Excellent (No Carryovers)

Student: Okoro wisdom
Performance: Very Good
Academic Status: Excellent (No Carryovers)

Student: Okorie joe
Performance: Good
Academic Status: Excellent (No Carryovers)

Student: Ekene madu
Performance: Good
Academic Status: Excellent (No Carryovers)

Student: Jonathan Samuel
Performance: Very Good
Academic Status: Excellent (No Carryovers)

Student: Mark King
Performance: Very Good
Academic Status: Excellent (No Carryovers)

Student: Samuel Elizabeth
Performance: Excellent
Academic Status: Excellent (No Carryovers)

Student: Amaka David
Performance: Very Good
Academic Status: Fair

Student: Okoro Emmanuel O
Performance: Very Good
Academic Status: Excellent (No Carryovers)

Student: Mark godson
Performance: Very Good
Academic Status: Excellent (No Carryovers)

Student: Emmanuel Victoria
Performance: Very Good
Academic Status: Excellent (No Carryovers)

Student: Williams ugo
Performance: Good
Academic Status: Excellent (No Carryovers)

Student: Victor urom
Performance: Good
Academic Status: Fair

Student: Chioma egwu
Performance: Good
Academic Status: Excellent (No Carryovers)

Student: Agwu Theresa
Performance: Very Good
Academic Status: Fair

Student: Onyekachi Nobel
Performance: Very Good
Academic Status: Fair

Student: Tessa chukwubuike
Performance: Good
Academic Status: Excellent (No Carryovers)

Student: Favour
Performance: Good
Academic Status: Excellent (No Carryovers)

Student: Peter Emmanuel
Performance: Very Good
Academic Status: Excellent (No Carryovers)

Student: Ewa divine
Performance: Very Good
Academic Status: Excellent (No Carryovers)

Student: Desmond Blessing
Performance: Good
Academic Status: Fair

Student: Divine
Performance: Very Good
Academic Status: Excellent (No Carryovers)

Student: Agha
Performance: Good
Academic Status: Fair

Student: Thompson
Performance: Good
Academic Status: Excellent (No Carryovers)

Student: Adline
Performance: Needs Improvement
Academic Status: Fair

Student: Precious
Performance: Very Good
Academic Status: Excellent (No Carryovers)

Student: Abdul Lawal
Performance: Good
Academic Status: Fair

Student: Rosemary
Performance: Good
Academic Status: Excellent (No Carryovers)

Student: Rhema
Performance: Very Good
Academic Status: Excellent (No Carryovers)

Student: Chibuzor
Performance: Good
Academic Status: Excellent (No Carryovers)

Student: Joyce
Performance: Excellent
Academic Status: Excellent (No Carryovers)

Student: Ugochi
Performance: Very Good
Academic Status: Excellent (No Carryovers)

Student: Splendor
Performance: Needs Improvement
Academic Status: Excellent (No Carryovers)

Student: Charity
Performance: Good
Academic Status: Excellent (No Carryovers)

Student: Rhems
Performance: Good
Academic Status: Excellent (No Carryovers)

Student: Faith
Performance: Very Good
Academic Status: Excellent (No Carryovers)

Student: John
Performance: Very Good
Academic Status: Excellent (No Carryovers)

Student: Emmanuella
Performance: Very Good
Academic Status: Excellent (No Carryovers)

Student: Hannah Clinton
Performance: Good
Academic Status: Excellent (No Carryovers)

Student: Rebecca
Performance: Good
Academic Status: Excellent (No Carryovers)

Student: Faith Adams
Performance: Good
Academic Status: Excellent (No Carryovers)

Student: Goodness
Performance: Very Good
Academic Status: Excellent (No Carryovers)

Student: Frederick
Performance: Very Good
Academic Status: Excellent (No Carryovers)

Student: Udu prince
Performance: Good
Academic Status: Excellent (No Carryovers)

Student: Daniel Effiong
Performance: Good
Academic Status: Excellent (No Carryovers)

Student: Agwu Victoria
Performance: Needs Improvement
Academic Status: Fair

Student: Felicia
Performance: Good
Academic Status: Excellent (No Carryovers)

Student: George Frank
Performance: Very Good
Academic Status: Excellent (No Carryovers)

Student: Godwin Philip
Performance: Good
Academic Status: Fair

Student: Dapo Adekunle
Performance: Very Good
Academic Status: Excellent (No Carryovers)

Student: Daniel Effiong
Performance: Very Good
Academic Status: Excellent (No Carryovers)

Student: Sevilla Chuks
Performance: Good
Academic Status: Fair

Student: Pius Jonathan
Performance: Very Good
Academic Status: Excellent (No Carryovers)

Student: Eze Faith
Performance: Very Good
Academic Status: Excellent (No Carryovers)

Student: Evangel Mark
Performance: Needs Improvement
Academic Status: Excellent (No Carryovers)

Student: Dennis Bayley
Performance: Excellent
Academic Status: Excellent (No Carryovers)

Student: Shanice astro
Performance: Very Good
Academic Status: Fair

Student: Isaac Ugoji
Performance: Good
Academic Status: Excellent (No Carryovers)

Student: Cynthia Eze
Performance: Excellent
Academic Status: Excellent (No Carryovers)

Student: David Florence
Performance: Good
Academic Status: Fair

Student: Trinity Winifred
Performance: Very Good
Academic Status: Excellent (No Carryovers)

Student: Divine Favour
Performance: Good
Academic Status: Excellent (No Carryovers)

Student: Frederick Leonard
Performance: Good
Academic Status: Excellent (No Carryovers)

Student: Destiny Brown
Performance: Good
Academic Status: Excellent (No Carryovers)

Student: Mgbada Peace
Performance: Excellent
Academic Status: Excellent (No Carryovers)

Student: Audrey Cyril
Performance: Very Good
Academic Status: Fair

Student: Meemeh Peter
Performance: Very Good
Academic Status: Excellent (No Carryovers)

Student: Ojim
Performance: Needs Improvement
Academic Status: Fair

Student: Martin
Performance: Good
Academic Status: Excellent (No Carryovers)

Student: Mary
Performance: Good
Academic Status: Excellent (No Carryovers)

Student: Chiamaka
Performance: Good
Academic Status: Excellent (No Carryovers)

Student: Izuchukwu
Performance: Very Good
Academic Status: Excellent (No Carryovers)

Student: Uchechi
Performance: Needs Improvement
Academic Status: Excellent (No Carryovers)

Student: Ibe Emmanuel
Performance: Good
Academic Status: Excellent (No Carryovers)

Student: Nancy
Performance: Good
Academic Status: Excellent (No Carryovers)

Student: Rachel
Performance: Good
Academic Status: Excellent (No Carryovers)

Student: Larsson
Performance: Good
Academic Status: Excellent (No Carryovers)

Student: Favour Emmanuel
Performance: Needs Improvement
Academic Status: Fair

Student: Chijioke
Performance: Needs Improvement
Academic Status: Fair

Student: James
Performance: Good
Academic Status: Excellent (No Carryovers)

Student: Princewill
Performance: Good
Academic Status: Fair

Student: Amanda
Performance: Good
Academic Status: Excellent (No Carryovers)

Student: Vincent
Performance: Good
Academic Status: Fair

In [8]:
required_skills = [
    "python",
    "sql",
    "git",
    "javascript"
]

for index, row in data.iterrows():

    print("\nStudent:", row["Full Name"])

    student_skills = str(row["Skills"]).lower()

    missing = []

    for skill in required_skills:

        if skill not in student_skills:
            missing.append(skill)

    print("Skills to Learn:")

    if len(missing) == 0:
        print("No additional skills recommended.")

    else:
        for skill in missing:
            print("-", skill)

Student: John
Skills to Learn:
- sql
- git
- javascript

Student: Prince otum
Skills to Learn:
- sql
- git
- javascript

Student: Flash
Skills to Learn:
- python
- sql
- git

Student: Chioma Monica
Skills to Learn:
- sql
- git
- javascript

Student: Egwuatu Kelechi Blessed
Skills to Learn:
- python
- sql
- git
- javascript

Student: Fred
Skills to Learn:
- python
- sql
- git
- javascript

Student: Rufus Deborah ogbonnaya
Skills to Learn:
- sql
- git
- javascript

Student: Sunday Samuel Ogo
Skills to Learn:
- python
- sql
- git
- javascript

Student: Isaac chinonso Mark
Skills to Learn:
- sql
- git
- javascript

Student: Ibekwe Mark Uchenna
Skills to Learn:
- python
- sql
- git
- javascript

Student: Nwabueze Emmanuel
Skills to Learn:
- python
- sql
- git
- javascript

Student: Ebeke Stephen agha
Skills to Learn:
- sql
- git
- javascript

Student: Samuel chinonso
Skills to Learn:
- python
- sql
- git

Student: Chinenye David
Skills to Learn:
- python
- sql
- git
- javascript

Student: Vincent Jeremiah Chidera
Skills to Learn:
- python
- sql
- git
- javascript

Student: Jeff Ekong
Skills to Learn:
- sql
- git
- javascript

Student: Idam Roseline
Skills to Learn:
- python
- sql
- git

Student: Emmanuel
Skills to Learn:
- sql
- git
- javascript

Student: Rhema
Skills to Learn:
- python
- sql
- git

Student: NWIBO SALOME OGBAGA
Skills to Learn:
- python
- sql
- git
- javascript

Student: Okoro wisdom
Skills to Learn:
- python
- sql
- git
- javascript

Student: Okorie joe
Skills to Learn:
- python
- sql
- git
- javascript

Student: Ekene madu
Skills to Learn:
- python
- sql
- git

Student: Jonathan Samuel
Skills to Learn:
- python
- sql
- git
- javascript

Student: Mark King
Skills to Learn:
- python
- sql
- git

Student: Samuel Elizabeth
Skills to Learn:
- python
- sql
- git
- javascript

Student: Amaka David
Skills to Learn:
- python
- sql
- git
- javascript

Student: Okoro Emmanuel O
Skills to Learn:
- python
- sql
- git
- javascript

Student: Mark godson
Skills to Learn:
- python
- sql
- git
- javascript

Student: Emmanuel Victoria
Skills to Learn:
- python
- sql
- git

Student: Williams ugo
Skills to Learn:
- sql
- git
- javascript

Student: Victor urom
Skills to Learn:
- sql
- git

Student: Chioma egwu
Skills to Learn:
- sql
- git
- javascript

Student: Agwu Theresa
Skills to Learn:
- python
- sql
- git

Student: Onyekachi Nobel
Skills to Learn:
- python
- sql
- git
- javascript

Student: Tessa chukwubuike
Skills to Learn:
- python
- sql
- git
- javascript

Student: Favour
Skills to Learn:
- python
- sql
- git

Student: Peter Emmanuel
Skills to Learn:
- python
- sql
- git
- javascript

Student: Ewa divine
Skills to Learn:
- python
- sql
- git
- javascript

Student: Desmond Blessing
Skills to Learn:
- python
- sql
- git
- javascript

Student: Divine
Skills to Learn:
- sql
- git
- javascript

Student: Agha
Skills to Learn:
- sql
- git

Student: Thompson
Skills to Learn:
- sql
- git
- javascript

Student: Adline
Skills to Learn:
- python
- sql
- git
- javascript

Student: Precious
Skills to Learn:
- python
- sql
- git
- javascript

Student: Abdul Lawal
Skills to Learn:
- sql
- git
- javascript

Student: Rosemary
Skills to Learn:
- sql
- git
- javascript

Student: Rhema
Skills to Learn:
- python
- sql
- git
- javascript

Student: Chibuzor
Skills to Learn:
- sql
- git

Student: Joyce
Skills to Learn:
- python
- sql
- git
- javascript

Student: Ugochi
Skills to Learn:
- sql
- git

Student: Splendor
Skills to Learn:
- python
- sql
- git

Student: Charity
Skills to Learn:
- sql
- git
- javascript

Student: Rhems
Skills to Learn:
- python
- sql
- git
- javascript

Student: Faith
Skills to Learn:
- python
- sql
- git

Student: John
Skills to Learn:
- python
- sql
- git

Student: Emmanuella
Skills to Learn:
- python
- sql
- git

Student: Hannah Clinton
Skills to Learn:
- python
- sql
- git
- javascript

Student: Rebecca
Skills to Learn:
- python
- sql
- git
- javascript

Student: Faith Adams
Skills to Learn:
- python
- sql
- git
- javascript

Student: Goodness
Skills to Learn:
- python
- sql
- git

Student: Frederick
Skills to Learn:
- sql
- git

Student: Udu prince
Skills to Learn:
- sql
- git

Student: Daniel Effiong
Skills to Learn:
- python
- sql
- git
- javascript

Student: Agwu Victoria
Skills to Learn:
- sql
- git

Student: Felicia
Skills to Learn:
- python
- sql
- git

Student: George Frank
Skills to Learn:
- python
- sql
- git
- javascript

Student: Godwin Philip
Skills to Learn:
- python
- sql
- git

Student: Dapo Adekunle
Skills to Learn:
- python
- sql
- git
- javascript

Student: Daniel Effiong
Skills to Learn:
- python
- sql
- git

Student: Sevilla Chuks
Skills to Learn:
- python
- sql
- git
- javascript

Student: Pius Jonathan
Skills to Learn:
- python
- sql
- git
- javascript

Student: Eze Faith
Skills to Learn:
- python
- sql
- git
- javascript

Student: Evangel Mark
Skills to Learn:
- python
- sql
- git
- javascript

Student: Dennis Bayley
Skills to Learn:
- python
- sql
- git

Student: Shanice astro
Skills to Learn:
- python
- sql
- git
- javascript

Student: Isaac Ugoji
Skills to Learn:
- python
- sql
- git
- javascript

Student: Cynthia Eze
Skills to Learn:
- python
- sql
- git
- javascript

Student: David Florence
Skills to Learn:
- python
- sql
- git
- javascript

Student: Trinity Winifred
Skills to Learn:
- python
- sql
- git

Student: Divine Favour
Skills to Learn:
- python
- sql
- git
- javascript

Student: Frederick Leonard
Skills to Learn:
- python
- sql
- git
- javascript

Student: Destiny Brown
Skills to Learn:
- python
- sql
- git

Student: Mgbada Peace
Skills to Learn:
- sql
- git
- javascript

Student: Audrey Cyril
Skills to Learn:
- python
- sql
- git
- javascript

Student: Meemeh Peter
Skills to Learn:
- python
- sql
- git
- javascript

Student: Ojim
Skills to Learn:
- sql
- git
- javascript

Student: Martin
Skills to Learn:
- python
- sql
- git
- javascript

Student: Mary
Skills to Learn:
- python
- sql
- git
- javascript

Student: Chiamaka
Skills to Learn:
- sql
- git
- javascript

Student: Izuchukwu
Skills to Learn:
- sql
- git
- javascript

Student: Uchechi
Skills to Learn:
- python
- sql
- git

Student: Ibe Emmanuel
Skills to Learn:
- sql
- git
- javascript

Student: Nancy
Skills to Learn:
- python
- sql
- git

Student: Rachel
Skills to Learn:
- sql
- git

Student: Larsson
Skills to Learn:
- sql
- git

Student: Favour Emmanuel
Skills to Learn:
- sql
- git

Student: Chijioke
Skills to Learn:
- python
- sql
- git

Student: James
Skills to Learn:
- python
- sql
- git

Student: Princewill
Skills to Learn:
- sql
- git

Student: Amanda
Skills to Learn:
- sql
- git
- javascript

Student: Vincent
Skills to Learn:
- sql
- git
- javascript

In [9]:
recommendations = []

for index, row in data.iterrows():

    cgpa = float(row["CGPA"])

    if cgpa >= 4.5:
        recommendations.append("Artificial Intelligence & Machine Learning")

    elif cgpa >= 3.5:
        recommendations.append("Software Engineering")

    elif cgpa >= 2.5:
        recommendations.append("Web Development")

    else:
        recommendations.append("Programming Fundamentals")

data["Final Recommendation"] = recommendations

print("Recommendations generated successfully.")

Recommendations generated successfully.

In [10]:
data.to_csv("student_recommendations.csv", index=False)

print("Recommendation file saved successfully.")

data

Recommendation file saved successfully.

,Full Name,Department,Skills,Programming Languages Known,Career Interest,Favourite Course,Career Goal,CGPA,Number of Carryovers,Final Recommendation
0,John,Computer Science,"HTML, CSS, Python, Problem Solving, UI/UX Design","Python, Java, C#, PHP",Web Development,Front end development,I love front end development,3.56,0,Software Engineering
1,Prince otum,Computer Science,Python,Python,Web Development,Database management,Artificial intelligence,3.32,0,Web Development
2,Flash,Computer Science,"HTML, CSS, JavaScript, Problem Solving, Database","Python, Java, C++, C#",Web Development,Cloud computing,Project Management,3.49,0,Web Development
3,Chioma Monica,Computer Science,"Python, Problem Solving, Database,","Python, Java, C++",Artificial Intelligence,Artificial intelligence,Data analysis,3.45,0,Web Development
4,Egwuatu Kelechi Blessed,Computer Science,UI/UX Design,HTML,Mobile Development,Frontend Development,Full stack,3.27,0,Web Development
...,...,...,...,...,...,...,...,...,...,...
97,Chijioke,Business Administration,"HTML, CSS, JavaScript","Python, Java, C#",Software Engineering,Database,Backend development,2.30,2,Programming Fundamentals
98,James,Business Administration,"HTML, CSS, JavaScript","Python, C++, C#",Artificial Intelligence,Front-End development,Backend development,3.03,0,Web Development
99,Princewill,Electrical Engineering,"HTML, CSS, Python, JavaScript","Python, Java, C++",Software Engineering,UI/UX Design,UI/UX Design,2.50,2,Web Development
100,Amanda,Information Technology,"HTML, Python, Problem Solving","Python, Java, C++",UI/UX Design,DevOps,Google Developer,3.40,0,Web Development
101,Vincent,Computer Science,"HTML, CSS, Python","Python, Java",Mobile Development,Software Engineering,Database design,2.70,1,Web Development